### ISSUE TITLE
Account balances table in Overview does not separate savings from checking balances

### ISSUE THREAD

**Issue by arhag** [aaroncox/vessel#12]
If you look at the account balances table with columns for "Available to Spend" and "Savings Account" you can see the problem for accounts that have non-zero savings balances. 

One  would expect the entries under the "Savings Account" column to contain the values for  `savings_sbd_balance` (for the SBD sub-column) and `savings_balance` (for the STEEM sub-column) and for the entries under the "Available to Spend" column to contain the values for `sbd_balance` (for the SBD sub-column) and `balance` (for the STEEM sub-column).

Instead, the entries under the "Savings Account" column are always 0, and the entries under the "Available to Spend" column have the total amounts for the account: the SBD sub-column under "Available to Spend" has a value of `sbd_balance+savings_sbd_balance` and the STEEM sub-column under "Available to Spend" has a value of `balance+savings_balance`.

**Comment by arhag** [comment]
And [here](https://github.com/aaroncox/vessel/blob/v0.0.6-a/app/components/Transactions/Balances.js#L36-L41) is where the problem is. The code does not make any distinction between savings or checking when determining the correct key to use for the `balances` object.

Note that correcting this bug would also require changing the calculation of totals [here](https://github.com/aaroncox/vessel/blob/v0.0.6-a/app/components/Transactions/Balances.js#L54-L59) to also include `SBD_SAVINGS` and `STEEM_SAVINGS` as part of the accumulation to ensure that the total calculation continues working correctly.

**Comment by aaroncox** [comment]
Thank you for making that an easy one to fix 😄
