### ISSUE TITLE
SP Delegation TAB not working/updating (windows)

### ISSUE THREAD

**Issue by 4Ykw** [aaroncox/vessel#16]
![image](https://cloud.githubusercontent.com/assets/6281545/26585147/67abb05a-459f-11e7-98f6-f8eec4eb336f.png)

**Comment by 4Ykw** [comment]
And if I go navigate on other menus and come back.. this appeared...
![image](https://cloud.githubusercontent.com/assets/6281545/26585323/db8d3cd2-459f-11e7-8448-32ce2dcf3ad1.png)

**Comment by aaroncox** [comment]
Give the new build a shot (0.0.6d), I think it resolves this.

https://github.com/aaroncox/vessel/releases/tag/v0.0.6-d

**Comment by 4Ykw** [comment]
Working now. Thanks.
