### ISSUE TITLE
Feature Suggestion: Steem Power Delegation

### ISSUE THREAD

**Issue by clayop** [aaroncox/vessel#2]
SP delegation is badly needed for growing community since it is a good way to empower and encourage active members. Can you set SP delegation as one of the priority?

**Comment by aaroncox** [comment]
I have a lot of the code and UI built out for it already, but I hit a small snag: there's no API's that I found that return the status of the SP you have delegated.

This means that I could build the UI to allow for delegation, but I couldn't offer a UI to stop delegation. A workaround for this would be to just store every time you delegate locally within the wallet - but if the delegation was done in the cli_wallet or some other method, or your wallet lost it's data, you wouldn't have any way to then cancel those other delegations.

What we really need for this to happen properly is a database API call on steemd for `get_delegated_vesting_shares`, allowing that information to be pulled and then displayed.

**Comment by aaroncox** [comment]
I've been shown the ways, and there is indeed a method for `get_vesting_delegations`. I'll get this workin.

**Comment by aaroncox** [comment]
Completed in v0.0.6 - release incoming.
