### ISSUE TITLE
Spacing issue in memo

### ISSUE THREAD

**Issue by clayop** [aaroncox/vessel#20]
It seems that vessel automatically remove space at the end of the box. But usually space is typed at the end while writing a sentence. So auto-removal for the memo box should be done when user click the preview button IMO.

**Comment by 4Ykw** [comment]
Yes, I confirm. But there is a workaround if you want to use spaces in the middle. Just go back and add them. I personally like the feature, but I agree with your suggestion.

**Comment by aaroncox** [comment]
Yeah it's trimming all excess space as you type, and you're right, that should probably happen on preview. I'll hopefully spend a day this week cleaning up some of these github issues.
