### ISSUE TITLE
Delegating SP to an user removed his delegated SP (from someone else).

### ISSUE THREAD

**Issue by 4Ykw** [aaroncox/vessel#23]
Not sure if this is related with Vessel, but once I have delegated to a user some SP, he lost his delegated one.

I have also lost a big portion (greater than I delegated) of SP I have been delegated to.

Can we confirm this one?

**Comment by aaroncox** [comment]
I'm a bit fuzzy on what situation occurred here. 

Are you saying once you delegated some SP to a user, he lost his delegation from Steemit? That might be the case, I know they're working on some logic to revoke delegated SP after account creation. 

Could you outline a bit more the exact scenario that occurred?

**Comment by 4Ykw** [comment]
Yes, I was a bit tired (had to rest). So, it all started on this post https://steemit.com/steemit-ideas/@forykw/powervoice-week-1-free-sbd-and-delegated-sp.

Throughout Vessel, I have given 6.720 SP to msg768 user and he lost all his SP. I have noticed that I have also lost some of SP that was being deleted to me. Then I tried giving the user what he said he lost 105 SP and he did not reset the previous delegated amount of the user, but it took a bunch more from the one that was being delegated to me.

Was not aware of any automatic revoking based on different users delegating to a single user. I would understand the concept, but not if does not take some curation period.

Something else I can't yet see to discover, is the VESTS revoking messages on the blockchain, do you know where are they?

Thanks for all the trouble. And, I know this is not Vessel bug, but felt you would like to know in advance. Since people that do not know will start complaining. Maybe put a warning on the delegation tab.

**Comment by 4Ykw** [comment]
Ok. Based on what I have learned [here](https://github.com/steemit/steem/issues/1182), I think there is nothing else to be done on this one. The user does not lost his SP, but it was tricky because a few hours before my delegation, steem has revoked msg768 all his SP. And it then looked like I have described above.

This all explained on the blockchain. Although is not easy to navigate through all that is happening.

The only suggestion I would make is to allow users that are delegating SP, to understand that if there any current delegation from you to that user, then the following one will replace the existing and NOT accumulate. So, if you want to add some more, you need to add yourself on the new delegation.

Besides that, all great the Vessel. Keep it up. I am closing since I am satisfied.

Cheers
