### ISSUE TITLE
Delegation "Date Revokable" - minor correction 

### ISSUE THREAD

**Issue by 4Ykw** [aaroncox/vessel#28]
![image](https://user-images.githubusercontent.com/6281545/27259517-24b5cd52-5469-11e7-8ee7-942c85a5ea78.png)

Wouldn't this be the date of the actual delegation? Like this is technically correct, but I believe that it causes a bit of confusion, no?

**Comment by aaroncox** [comment]
Yeah I think I misunderstood what exactly the date meant when I was building it. Good catch!
