### ISSUE TITLE
Feature request: Allow entering in specific numbers when delegating VESTS

### ISSUE THREAD

**Issue by arhag** [aaroncox/vessel#29]
It would be nice to be able to input the precise amount of VESTS one wishes to delegate in the UI rather than being forced to use the slider which has limited resolution.

**Comment by 4Ykw** [comment]
Yes, this is what we were talking in https://github.com/aaroncox/vessel/issues/18

**Comment by arhag** [comment]
Oops. Sorry for the duplicate. I'll close this issue.
