### ISSUE TITLE
'Operation Error' when powering down

### ISSUE THREAD

**Issue by buzzbeergeek** [aaroncox/vessel#31]
I have some delegated amount already. Any ideas? 

Thanks!

@buzzbeergeek

**Comment by aaroncox** [comment]
The operation errors come back directly from the Steem blockchain. Were you trying to powerdown an amount that would dip into what you've got delegated currently?

**Comment by buzzbeergeek** [comment]
That is exactly the issue! I took me an hour of staring into the numbers to figure it out! Thanks for the quick reply! Vessel is wonderful!
