### ISSUE TITLE
Question: are keys hierarchically determined?

### ISSUE THREAD

**Issue by rgenito** [aaroncox/vessel#37]
Are keys determined hierarchically? If I could add the question tag, I would've...thank you! :)

https://bitcoin.org/en/glossary/hd-protocol
https://bitcoinmagazine.com/articles/deterministic-wallets-advantages-flaw-1385450276/

**Comment by aaroncox** [comment]
No, Vessel/Steem don't use hierarchically determined keys like that, since you send from an account to an account, rather than from address to address. So it's not HD in that sense.
