### ISSUE TITLE
says my key is invalid, but I am using it on steemit, so I'm pretty sure it's my key

### ISSUE THREAD

**Issue by inquiringtimes** [aaroncox/vessel#43]
I downloaded vessel 0.0.7 (deb) and installed on Linux Mint 18.2 (64bit)

trying to set up... however.. it seems confused

<img src="http://imgur.com/bcmP6aZl.png" />

not sure if I will get notified about a response here, but you know how to find me @jesta same name on discord or steemit.chat 

Thank You!

- @inquiringtimes

**Comment by aaroncox** [comment]
Is it a key or a password? 

That screen looks like the name/password screen, which only works with the master password (starts with the letter P). 

If you're using a key (starts with 5), go back a screen and use the 2nd option to import a key. 

Hope that helps, let me know if it's still not working.

**Comment by inquiringtimes** [comment]
uh.... it says "permissions for wallet: Active"  

I did not anticipate needing my master key, when I selected active permissions

**Comment by inquiringtimes** [comment]
ok.  Done Did it... that was confusing... so maybe more straight forward UI will be helpful in the future.

thank you!

**Comment by aaroncox** [comment]
I agree - the UI could use some work. 

The terminology used on the first/second window during that process are accurate - but it's also complicated.

**Comment by inquiringtimes** [comment]
yeah, def not complaining!  this is such an awesome app.  can't wait for the mobile version
