### ISSUE TITLE
Heroku fails to build vessel (Desktop wallet for steem blockchain)

### ISSUE THREAD

**Issue by shreyasgune1** [aaroncox/vessel#48]
Heroku is a *platform as a service (PAAS)* that lets you deploy apps online. It is an amazing service which is very popular and free for light use.

I tried to deploy the vessel wallet for steam through heroku. The build failed. I will first explain simple step by step procedure to replicate the problem and then I will share the build log.

This is how you duplicate the problem:

1. Clone the [github repository](https://github.com/aaroncox/vessel) into your own repository.
![Screen Shot 2017-11-09 at 12.59.31 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510169404/hcyttepn6ps2cfgxa3fb.png)

2. Login to your [heroku account](https://id.heroku.com/login).  If you don't have an account create one. It is an almost instantaneous process. You will only need to verify your email.

3. Click on New and then select *Create an app*.
![Screen Shot 2017-11-09 at 1.01.57 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510169544/c4jnwxfihvl9cqr0zgo5.png)

3. Give the app any name. I will name it vesselwallet (vessel name is unavailable). Then click on *Create app*.
![Screen Shot 2017-11-09 at 1.08.44 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510170088/g74a0t6qceblhbpwqi5p.png)

4.Page, as shown below, appears. Dont choose any pipeline. Choose *github* as deployment method.
![Screen Shot 2017-11-09 at 1.13.25 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510170301/xies2as73vjnthpjru8e.png)

5. Select your cloned repository. A message as shown below will be displayed which tells you that your github repository has been sucessfully connected.
![Screen Shot 2017-11-09 at 1.18.49 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510170580/fxvknsstzhjypnbw7ux8.png)

6. In Manual Deployment, just select deploy branch.

7. The app build fails with log:
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 6.x...
       Downloading and installing node 6.12.0...
       Using default npm version: 3.10.10
       Resolving yarn version 0.28.4...
       Downloading and installing yarn (0.28.4)...
       Installed yarn 0.28.4
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.28.4
       [1/4] Resolving packages...
       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
 !     Outdated Yarn lockfile
       Your application contains a Yarn lockfile (yarn.lock) which does not
       match the dependencies in package.json. This can happen if you use npm
       to install or update a dependency instead of Yarn.
       Please run the following command in your application directory and check
       in the new yarn.lock file:
       $ yarn install
       $ git add yarn.lock
       $ git commit -m "Updated Yarn lockfile"
       $ git push heroku master
    
       https://kb.heroku.com/why-is-my-node-js-build-failing-because-of-an-outdated-yarn-lockfile
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

```
Thanks You.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@shreyasgune/heroku-fails-to-build-vessel-desktop-wallet-for-steem-blockchain">Utopian.io</a></em><hr/>

**Comment by aaroncox** [comment]
Vessel won't work on Heroku - since heroku is designed to host web applications. Vessel is designed to be a desktop application (using electron) and not to be run a browser. 

Not sure what you're trying to do - but this won't work 😄

**Comment by shreyasgune1** [comment]
Can docker deploy it though ? Trying to test out the code as a noob and learn in the process !!

**Comment by aaroncox** [comment]
Docker could build the executable but I'm not really sure it would work for development. 

Vessel outputs an executable file which then runs a GUI - both Docker and Heroku are headless environments without a GUI interface, which is why I don't think it would work.
