### ISSUE TITLE
hangs on Height Loading after account creation

### ISSUE THREAD

**Issue by stuffo** [aaroncox/vessel#54]
Used the appimage package 0.9. After adding my account credentials the app just does nothing. The only message is "Height Loading" in the lower left corner. But nothing changes for a long time now. 
Restarting it or deleting the config and adding the account again doesn't change anything. Here is the output of the dev console:

```
action ACCOUNT_DATA_UPDATE_PENDING @ 22:06:25.812 core.js:104  
action ACCOUNT_DATA_UPDATE_PENDING @ 22:06:35.811 core.js:104  
...
```
Using Arch Linux. Keep up the great work! Thx.

**Comment by aaroncox** [comment]
I think this is because the default node went offline earlier today. 

If you goto settings and change the node to `https://api.steemit.com` for the time being, it should resume working.

**Comment by stuffo** [comment]
thanks for the answer. rpc.buildteam.io works. the api.steemit.com seems to talk a different protocol and doesn't.
