### ISSUE TITLE
No login after password and username

### ISSUE THREAD

**Issue by smike18** [aaroncox/vessel#68]
After entering the username, Steemit.com password and the Wallet password, the circle on the wallet loads all the time. 
After about 10-15 minutes I stop. 

And I can´t login.

**Comment by aaroncox** [comment]
What version is this happening on? Is this an additional account or the initial setup of a brand new install? 

From the sounds of it, you're just not connected to a steemd node and the forever loading is because of that.

**Comment by smike18** [comment]
I've installed it new today its Vessel 0.2.0
I click on "Import steemit account" and put all info in. 

How can I get connected with the steemd node? There is no setting I can find.

**Comment by onthax** [comment]
think this might be a duplicate of the one i just raised https://github.com/aaroncox/vessel/issues/69

**Comment by aaroncox** [comment]
It sounds like it is, and I also just posted a solution into #69 :)

**Comment by aaroncox** [comment]
0.2.5 now has a preferred steem node option on the bottom of the initial welcome screen, allowing for changing when this happens.
