### ISSUE TITLE
not showing the right wallet values

### ISSUE THREAD

**Issue by stresskiller** [aaroncox/vessel#72]
on powering up the wallet shows old values and not he new ones , even if you change
the RPC node it won't show the correct value

version i'm using : 2.0 win 64

**Comment by stresskiller** [comment]
just installed the newer version 0.2.5 problem is still there

**Comment by fraenk** [comment]
have you tried changing the RPC node?

**Comment by stresskiller** [comment]
@fraenk thank you but i  just tried that no result ..

**Comment by stresskiller** [comment]
the steemit account is @stresskiller , @bokeh and @macrophotography  

it still shows that i have 30 SBD that i already transferd , it used to be up to date when you started the program

**Comment by aaroncox** [comment]
Hrm, it really does sound like you're connected to a bad node, but if you changed nodes, that shouldn't be happening. Mind sending me a screenshot of the overview panel so I can see what exactly is being displayed vs what a block explorer shows?

**Comment by stresskiller** [comment]
ok here you go

![vessel-feedback](https://user-images.githubusercontent.com/27805665/34899229-e72d3e4c-f7f7-11e7-9d00-7e48b29db9c1.jpg)

**Comment by aaroncox** [comment]
From the looks of it (seeing block 18909347 in the lower left), you've lost connection to the blockchain itself. That block is about 19 hours old, and the transfer you did of that SBD is about 15 hours old. 

Change the Preferred Steem Node server to `https://rpc.buildteam.io` or `https://steemd.privex.io` in the settings, it should reconnect, and the balances should be correct.

One of the other features I am going to roll out in the next week or so is a better way for Vessel to realize if it's connected or not, and then provide easier options to reconnect.

**Comment by stresskiller** [comment]
https://rpc.buildteam.io seems to work for now already tried:
https://steemd.privex.io
 http://api.steemit.com and minnowsupportproject.org before without the right results

**Comment by aaroncox** [comment]
`0.2.6` was just released a few moments ago - if the issue reoccurs please try again with the updated version!
