### ISSUE TITLE
vessel 0.2.5 immediately downloads code from cloudflare cdnjs to execute on run

### ISSUE THREAD

**Issue by sneak** [aaroncox/vessel#74]
![screen shot 2018-01-12 at 15 51 53](https://user-images.githubusercontent.com/408977/34896752-a97467d4-f7b0-11e7-84c0-321e56d4c259.png)

This is a security vulnerability, as Cloudflare can then serve whatever JS it wants.  The point of an offline app is to encapsulate the dependencies so that the user can control what code is being run.  Downloading and running code from the network makes this no more secure than a browser app.

**Comment by aaroncox** [comment]
https://github.com/aaroncox/vessel/blob/11a5996927e0d459e25229a09ac65cb3976d61df/app/app.html#L6

Initially I had issues getting the semantic-ui CSS builder to integrate into the electron application, so I included the CSS from CDN-JS with the SHA integrity check. I need to revisit this again, and if I can't get semantic-ui's built in generator to work, I'll just manually bundle the CSS within the application so the external request is no longer required.

I'll plan to have this in 0.2.6.

**Comment by aaroncox** [comment]
To follow up - I couldn't get the builder to function properly, so I've taken a prebuilt version of semantic-ui, modified it, and injected it directly into the app in https://github.com/aaroncox/vessel/commit/ae4ad01aa3f4212b80be428195d1890d6bf08616. This removes the only external dependency request.

**Comment by aaroncox** [comment]
`0.2.6` released with the code above, thanks again sneak!
