### ISSUE TITLE
vessel doesn't initiate on macOS 

### ISSUE THREAD

**Issue by whitas** [aaroncox/vessel#77]
Hi, I'm not able to create new wallet, neither import existing account / keys. Only thing I see is spinning circle after I accept text values in text boxes. The same issue on stage when I'd try to create new key. Program stucks on "checking" next to the username input box.

Platform - macOS High Sierra. 
vessel version 0.2.5

**Comment by aaroncox** [comment]
There's been a rash of public servers going down the past week, which is at the heart of this problem. 

I'd recommend using the "Preferred Steem Node" section at the bottom and setting it to one of the following:

```
https://gtg.steem.house:8090
https://seed.bitcoiner.me
https://rpc.buildteam.io
https://steemd.privex.io
https://steemd.steemitstage.com
```

**Comment by whitas** [comment]
Thank you for response, I assumed that it was the communication issue but couldn't find any list of active rpc servers. Thank you for this. It worked.

**Comment by aaroncox** [comment]
No problem! I'm working on making the issue more visible within the wallet, and providing a list of servers to choose from within the UI itself. Hopefully next release!
