### ISSUE TITLE
Not able to create vessel account on osx

### ISSUE THREAD

**Issue by malick147** [aaroncox/vessel#80]
Creating a vessel account when you first start the app after installation on osx doesn't work. It ends up in showing the loading icon for forever. 
At first I thought it takes its time to encrypt the account but after 7 hours I canceled the process and tried it without encryption. Same problem. Loading icon keeps spinning for forever.

**Comment by aaroncox** [comment]
What version was this?

**Comment by malick147** [comment]
0.2.0

**Comment by aaroncox** [comment]
Much of this is fixed in the newest versions, try upgrading to 0.2.6

**Comment by malick147** [comment]
Hmm alright... I changed first changed the version from 0.2.6 to 0.2.0 beause I thought it might be a new bug.. Upgraded back to 0.2.6 now it works. 
Thanks for the help

**Comment by aaroncox** [comment]
No problem!
