### ISSUE TITLE
Delegation given in account creation takes longer than expected to become available after cancellation.

### ISSUE THREAD

**Issue by fraenk** [aaroncox/vessel#82]
Hi @aaroncox ,

This may in fact not be a bug at all, maybe this is in fact intended by steem rules?

I have created a new account through vessel. The account gets created with 0.1 SP and 14.5 SP delegation.

I did cancel the delegation 10 days ago but the delegated Vests have not been made available for the creating account again, yet.

Is there a different "cooldown" for these delegations made during account creation or might this actually be a bug?

P.S.:
account creation: https://steemd.com/tx/e1858b1d252e6ec2cc071fe595f7aa802eef6435
canceled delegation: https://steemd.com/tx/556d9d090a825e98566d5e96876f8c7fa02b8089

**Comment by aaroncox** [comment]
Ahh yes, the account creation delgations have a different return policy than just straight delegations.

If you delegate to create an account, the return after you revoke is 30 days. But if you revoke a delegation that was just delegation to an already existing account, that's 7 days.

**Comment by fraenk** [comment]
Ahh... ok... everybody I had asked so far assured me that it should be the same 7 days.

Thanks for the clarification! I'll close this issue then!
