### ISSUE TITLE
Does This Wallet Even Work? (Yes very well, fixed)

### ISSUE THREAD

**Issue by CSUSBgeochem1** [aaroncox/vessel#92]
No disrespect to the author what so ever but i have tried multiple systems with no success. My current system is running Linux Mint and i have two issues.  It constantly drops the connection with the node, no matter what node i choose.  The second is i can not even add an account, no matter what password i choose it tells me the WFI key is incorrect. Even though the green button loads, when i click it i get no response.  I have tried it on a windows 7 system with similar problems.

**Comment by aaroncox** [comment]
There are a lot of node issues lately. In one of the next versions I'll be changing the default to `https://wallet.steem.ws`, which is a node I personally run that's dedicated/tailored for wallet usage. I'd recommend trying to change your node to that and see if it resolves the connection issues. 

In regards to adding an account - are you actually importing a WIF key or are you using a master password? The WIF keys start with `5` followed by random characters, where as the master passwords start with `P5`. 

The clicking and not getting a response might be related to the node issues you're talking about as well - it connects to validate that the key you enter resolves to the public key of the existing account.

**Comment by CSUSBgeochem1** [comment]
Man i am happy as can be right now, i figured i would test the previous version to see if i had similar issues and it seems to have fixed everything.  I have yet to have any node issues and i was able to create an account and access everything. It was the master i was importing. I wonder what the issue is with the .0.2.7 version.
