### ISSUE TITLE
error on account creation 

### ISSUE THREAD

**Issue by ShadowsPub** [aaroncox/vessel#96]
Was creating 3 accounts, two went though with no problem. Third one generated the error message, "missing an  active authority" 

the account name was 17 characters in case that has an affect.

**Comment by Jolly-Pirate** [comment]
It's maximum 16 characters.

**Comment by aaroncox** [comment]
In any case, the error should probably be a bit more clear 👍

**Comment by ShadowsPub** [comment]
thanks .. wondered if the length may have been the problem
